#dev 环境的配置
#
#server:
#  port: 8090

spring:
  jdbc:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_01
      username: dev
      password: dev
      type: c3p0 #用于多数据源哦安装 c3p0或druid