spring:
  web:
    resources:
      static-locations: classpath:/webapp/
  datasource:
    url: jdbc:mysql://localhost:3306/root/java
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver